<?php

/**
 * @file
 *  The main file for the Brafton Importer module
 */

/**
 * Implements hook_cron().
 *
 * Imports XML articles on schedule.
 */
function brafton_importer_cron() {

//  $queue = \Drupal::queue('brafton_cron');

//  \Drupal\brafton_importer\BraftonImporterService::createBraftonArticle();

//  \Drupal::service('brafton_importer.brafton_importer_service')->createBraftonArticle();

    $article_loader = new \Drupal\brafton_importer\Model\BraftonArticleLoader();
    $article_loader->import_articles();

}


/*
$new_node_info = array( ,
  'type' => 'article',
  'title' => 'New testing article'
);

$new_node = entity_create('node', $new_node_info);
$new_node->save();
*/
?>
